/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.ui.GameFrame;

public class App {

    public static void main(String[] args) {
    	new GameFrame("Snake");
    }
}
